version: '3.8'

services:
 db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB:  ${DATABASE_NAME}
    ports:
      - 5432:5432
    container_name: alpha_db

 web:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/bin/bash', './entrypoint.sh']
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      NODE_ENV:  ${NODE_ENV}
      DATABASE_PORT:  ${DATABASE_PORT}
      DIALECT:  ${DIALECT}

volumes:
  postgres-data:
